export const notificationList = [
  // {
  //   img: "/images/",
  //   incAccName: "",
  //   groupName: "",
  //   message: "",
  //   isRead: false,
  //   postName: "",
  //   postImg: "",
  //   postInfo: "",
  //   postTime: "",
  // },
  {
    id: "1",
    img: "/images/avatar-mark-webber.webp",
    incAccName: "mark webber",
    isRead: false,
    postInfo: "reacted to your recent post",
    postTime: "1m ago",
    postName: "My first tournament today!",
  },
  {
    id: "2",
    img: "/images/avatar-angela-gray.webp",
    incAccName: "angela grey",
    isRead: false,
    postInfo: "followed you",
    postTime: "5m ago",
  },
  {
    id: "3",
    img: "/images/avatar-jacob-thompson.webp",
    incAccName: "jacob thompson",
    groupName: "Chess Club",
    isRead: false,
    postInfo: "has joined your group",
    postTime: "1 day ago",
  },
  {
    id: "4",
    img: "/images/avatar-rizky-hasanuddin.webp",
    incAccName: "rizky hasanuddin",
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    isRead: true,
    postInfo: "sent you a private message",
    postTime: "5 days ago",
  },
  {
    id: "5",
    img: "/images/avatar-kimberly-smith.webp",
    incAccName: "kimberly smith",
    isRead: true,
    postImg: "/images/image-chess.webp",
    postInfo: "commented on your picture",
    postTime: "1 week ago",
  },
  {
    id: "6",
    img: "/images/avatar-nathan-peterson.webp",
    incAccName: "nathan peterson",
    isRead: true,
    postName: "5 end-game strategies to increase your win rate",
    postInfo: "reacted to your recent post",
    postTime: "2 weeks ago",
  },
  {
    id: "7",
    img: "/images/avatar-anna-kim.webp",
    incAccName: "anna kim",
    isRead: true,
    groupName: "Chess Club",
    postInfo: "left the group",
    postTime: "2 weeks ago",
  },
];
